version: '3.4'
services:
  lbl:
    build:
      context: ./load-balancer/
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 6

#  esb-mgr:
#    build: ./wso2-esb-manager/
